### PR TITLE
sdk: don't allow mounts in inject actions

### PR DESCRIPTION
**Pull request by chrisguida**
Fixes: https://github.com/Start9Labs/embassy-os/issues/557

Proof:
Screen Shot 2022-07-14 at 7 02 13 PM
Screen Shot 2022-07-14 at 7 02 46 PM

### CODE REVIEW

**Comment by dr-bonez** [comment]
since `verify()` is invoked on package install as well, we may need to only run this check if `manifest.eos-version >= 0.3.2`

**Comment by chrisguida** [comment]
I'd prefer to know on the pack step, not on the install step

**Comment by chrisguida** [comment]
Or perhaps I'm misunderstanding

**Comment by dr-bonez** [comment]
It does both

**Review by dr-bonez — APPROVED** [review]

**Pull request merged**
