### PR TITLE
Integration/0.2.11

### PR DESCRIPTION
**Pull request by elvece**

### CODE REVIEW

**Comment by dr-bonez** [comment]
Why was this closed?

**Comment by elvece** [comment]
I closed this because it was already merged, and I had pushed reverting changes (to revert `package-lock.json`) since we thought this might be contributing to the looped refresh issue. I was experiencing rebase issues and decided to open up a new branch instead of rehashing this one.

New [branch](https://github.com/Start9Labs/embassy-os/pull/250) - going to also close since now irrelevant.

**Comment by dr-bonez** [comment]
There is no evidence of this already being merged as far as I can tell. Make sure that every important change on this branch makes it to master before 0.2.11 is cut.

**Comment by ProofOfKeags** [comment]
There are conflicts going into master. I think we should resolve, merge, build and then test before pushing out to production.

**Review by ProofOfKeags — APPROVED** [review]

**Pull request merged**
