### PR TITLE
only validate mounts for inject if eos `>=0.3.1.1`

### PR DESCRIPTION
**Pull request by dr-bonez**

### CODE REVIEW

**Review by MattDHill — APPROVED** [review]

**Comment by chrisguida** [comment]
What's the purpose of this? I thought we decided not to worry about backwards compatibility since inject docker actions literally won't run if they have mounts defined

**Comment by dr-bonez** [comment]
@chrisguida the inject flag is ignored for certain types of actions

**Comment by chrisguida** [comment]
Which actions? Did those actions exist prior to 0.3.1.1?

**Comment by dr-bonez** [comment]
backup restores is where we ran into this

**Comment by chrisguida** [comment]
Ok, so the effect of this PR is to allow inject actions to have mounts on packages older than 0.3.1.1? Do we want users to be able to install packages whose backup restores are invalid?

**Pull request merged**
