### PR TITLE
trust local ca

### LINKED ISSUE #1642: [bug]: Embassy does not accept its own certificate authority
The embassy CA needs to be installed to the trust chain of the OS

### PR DESCRIPTION
**Pull request by dr-bonez**
closes #1642

### CODE REVIEW

**Review by chrisguida — DISMISSED** [review]
Seems right

**Comment by dr-bonez** [comment]
Tested

**Comment by chrisguida** [comment]
What changed in the force push?

**Comment by dr-bonez** [comment]
just rebased against master

**Review by MattDHill — APPROVED** [review]

**Pull request merged**
