### PR TITLE
add accordion-instructions component and include in app-installed-show

### PR DESCRIPTION
**Pull request by satoshisound**
Reference issue: https://github.com/Start9Labs/embassy-os/issues/309

Simple accordion for displaying instructions as per suggestion by @ProofOfKeags.

### CODE REVIEW

**Comment by MattDHill** [comment]
Changed base to my current working branch, which is a massive under-the-hood refactor of the ui to switch over to websocket infra and new data model, amongst other things. Preparing to integrate a new mocking structure in the next 24 hours. Then we can test this out.

**Comment by ProofOfKeags** [comment]
@satoshisound do you feel like you can resolve the commit conflicts?

**Comment by satoshisound** [comment]
@ProofOfKeags I believe @MattDHill said that the new design in 0.3.0 doesn't necessitate this accordion feature anymore. What's the consensus? Happy to work on it if it will be used.

**Comment by MattDHill** [comment]
Yeah, an accordion no longer makes sense with redesigned interface, which is still being worked on. Once the redesign is complete, we can get together and identity areas for improvement and carve it up. Very happy to have your interest, please stick around!

**Pull request closed without merging**
