### PR TITLE
set owner

### PR DESCRIPTION
**Pull request by dr-bonez**
closes https://github.com/Start9Labs/synapse-wrapper/issues/23

### CODE REVIEW

**Review by Blu-J — APPROVED** [review]

**Comment by chrisguida** [comment]
Does not build

```
error[E0382]: borrow of moved value: `m`
   --> src/setup.rs:406:35
    |
380 |                 let m = e.metadata().await?;
    |                     - move occurs because `m` has type `std::fs::Metadata`, which does not implement the `Copy` trait
...
391 |                     tokio::task::spawn_blocking(move || {
    |                                                 ------- value moved into closure here
...
394 |                             Some(Uid::from_raw(m.uid())),
    |                                                - variable moved due to use in closure
...
406 |                     ctr.fetch_add(m.len(), Ordering::Relaxed);
    |                                   ^^^^^^^ value borrowed here after move

For more information about this error, try `rustc --explain E0382`.
warning: `embassy-os` (lib) generated 15 warnings
error: could not compile `embassy-os` due to previous error; 15 warnings emitted
make: *** [Makefile:57: appmgr/target/aarch64-unknown-linux-gnu/release/embassyd] Error 101

```

**Comment by chrisguida** [comment]
Just one more change is needed. The `main` directory itself needs also to be owned by `991`. I achieved this by typing `chown 991:991 .` inside `/embassy-data/package-data/volumes/synapse/data/main`.

**Comment by dr-bonez** [comment]
@chrisguida try now

**Comment by chrisguida** [comment]
I'm stuck on this until I can set up. Hitting this error no matter what I do:

Screen Shot 2022-01-04 at 7 31 05 PM

**Review by chrisguida — APPROVED** [review]

**Pull request merged**
