### PR TITLE
fix: Closed file

### PR DESCRIPTION
**Pull request by Blu-J**
### About

Potentially I am trying to fix 
image

And my theory is that since I am no longer consuming the buffer it is going into a state of EOF.

### Proof Of Fix

- [x] Test deployment to a pi, restart scanning of blocks

### CODE REVIEW

**Comment by Blu-J** [comment]
image

**Comment by Blu-J** [comment]
We get the git info of 
image
And the git log
image

Proving we are on the embassyd version that we are expecting

**Comment by Blu-J** [comment]
For also testing that there is no memory leak after x hours


image

**Comment by Blu-J** [comment]
Preliminary, looks like it works

**Comment by Blu-J** [comment]
image
Seems to have fixed, not sure there is or not a memory leak though

**Review by elvece — APPROVED** [review]

**Pull request merged**
